
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/inventrydb?createDatabaseIfNotExist=true
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
 
      
  
 